language: python
python:
    - "3.6" 
cache: pip
before_script: 
    - easy_install distribute  
    - pip install -r requirements.txt  
    - pip install pycodestyle
script:
    - pycodestyle hangman.py
    - python hangman.py < guess.txt
